### ISSUE TITLE
Saving the benchmark graphs

### ISSUE THREAD

**Issue by ChatterjeeAyan** [google-research/graphworld#7]
Is there a way to save all the benchmark graphs generated (preferably in networkx graph format)?

**Comment by jpalowitch** [comment]
In [`main_local_mwe.sh`](https://github.com/google-research/graphworld/blob/main/main_local_mwe.sh), add the [`--write_intermediate`](https://github.com/google-research/graphworld/blob/5a9bced51deca6ee32bcd7b69c18f27816237380/src/graph_world/beam/pipeline.py#L52) flag to the run command.
